# Joint Trajectory Controller
rl_dp_5_controllers_position:
    type: position_controllers/JointTrajectoryController
    joints: 
        - joint_1  
        - joint_2
        - joint_3  
        - joint_4  
        - joint_5  
    gains:
      joint_1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
      joint_2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
      joint_3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
      joint_4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
      joint_5: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}