controller_list:
    - name: /rl_dp_5/controllers/position
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5